"""empty message

Revision ID: 67417183bffa
Revises: 0aea5a9c7f88
Create Date: 2024-10-11 20:40:11.309400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67417183bffa'
down_revision = '0aea5a9c7f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_path'), ['path'], unique=False)
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_document_path'))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
